<div class="footer-container">
    <div class="footer">

        <div class="footer-logo"></div>

        <div class="footer-product-category">
            <ul>
                <li><a href='/wine.html'>wine</a></li>
                <li><a href='/beer.html'>beer</a></li>
                <li><a href='/spirits.html'>spirits</a></li>
                <li><a href='/merchandise.html'>merchandise</a></li>
                <li><a href='/pick six.html'>pick six</a></li>
                <li><a href='/tastings.html'>tastings</a></li>
                <li><a href='/delivery.html'>delivery</a></li>
                <li><a href='/learn.html'>learn</a></li>
            </ul>
        </div>

        <div class="footer-social-links">
            <?php echo $this->getChildHtml() ?>

            <ul>
                <li><a href='https://www.facebook.com/' target="_blank">facebook</a></li>
                <li><a href='https://twitter.com/' target="_blank">twitter</a></li>
                <li><a href='https://instagram.com/' target="_blank">instagram</a></li>
            </ul>
        </div>

        <div class="footer-info">
            <h5>tweet</h5>

            <p>Brady`s <span>@bradyswinewarehouse</span></p><br>

            <p><em>Lorem ipsum dolor sit amet, consectetur adipiscing elit.Aliquam vulputate nisi.<br><span>www.winewednesday.com</span></em>
            </p>
        </div>
        <address class="copyright"><?php echo $this->getCopyright() ?></address>
    </div>
</div>